# This file was generated by GoReleaser. DO NOT EDIT.
cask "repoguide" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "3239906a39aec734987dbebe4ad24e8314bb6cc2e7d9387e01ce66d4afa36d4d"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "26f78977a3671cd2d472bf174f75330b8d450e95d5af427bbbb411160344274d"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "9b8b06c40eb9e077ee231b43a40e2cca9a7cbd2ccc15b92429db733e7307295b"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be2632fbde618a7a9414b7bb00e340058b238f1bc02e12cd75a3d21bf183ac39"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repoguide"
  desc "Replay and learn from your AI coding sessions"
  homepage "https://repoguide.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repoguide"

  # No zap stanza required

end
