# This file was generated by GoReleaser. DO NOT EDIT.
cask "repoguide" do
  version "0.15.1"

  on_macos do
    on_intel do
      sha256 "c595489f8e8c4bff1da546ce3a28e34924e04411bbc20805ee2b7b121dd8c210"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "0ad27f690122568ee5c01a9eb4496e170ae42d817371c9787912e91ecf33ddd4"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfce07ab1681be3109d8c0e568d7903dc78eadb588fd0bd9b18e2f17daaef82d"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aee1e36d15543022ca56e54b6d00b41506a9b6a2bfcb61ad446a7bfffb9aa888"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repoguide"
  desc "Replay and learn from your AI coding sessions"
  homepage "https://repoguide.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repoguide"

  # No zap stanza required

end
