# This file was generated by GoReleaser. DO NOT EDIT.
cask "repoguide" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "43cff0a7a7a11c88462ff6288201c6e1ce1ee25cb408c963f654f8e086043d18"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7689273d3f6a16c61f90a6f0005df6ccb15a9e70731e01c184ea369cb2709f8f"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "49e56a3f321fd05989e1f8553e37261a71bd042e264b219a23c46fff52da9a08"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c56f3ad200b01741a9d93e0a0f58c0eabf20e1437c37c3cff3d2c88c55cd5d87"
      url "https://github.com/repoguide-dev/repoguide-releases/releases/download/v#{version}/repoguide_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repoguide"
  desc "Replay and learn from your AI coding sessions"
  homepage "https://repoguide.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repoguide"

  # No zap stanza required

end
